name: LantersLanterns
favicon: null
layout_spectrum: 0.5257434493396431
typography_spectrum: 0.3925392075907439
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.502898485166952
  lightness: 0.10490767005831003
  saturation: 0.5606359955854714
  rhythmicContrast: 0.0645983568392694
purpose: []
